name: deploy_api

on:
  workflow_dispatch:
    inputs:
      env:
        description: "dev | prd"
        default: "dev"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GCP_REGION: asia-northeast1
      IMAGE: 'asia-northeast1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_REPOSITORY }}/api'
      TAG: '${{ github.sha }}'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure gcloud
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/platform managed
          gcloud config set run/region ${{ env.GCP_REGION }}
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev
      - name: Build docker image
        run: docker image build --platform linux/amd64 -t ${IMAGE}:${TAG} --target release .
      - name: Push docker image
        run: docker image push ${IMAGE}:${TAG}
      - name: Deploy docker image to Cloud Run
        run: gcloud run deploy api --image ${IMAGE}:${TAG}
